name: ml-argo-n2o
channels:
  - pytorch
  - pyg
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - scikit-learn
  - xarray
  - matplotlib
  - cartopy
  - seaborn
  - pyarrow
  - python-dotenv
  - pip
  - pip:
      - gsw
