name: ml-argo-n2o
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - xarray
  - matplotlib
  - cartopy
  - seaborn
  - pip
    - pip:
      - gsw
